services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  external-ledger:
    build:
      context: ../external.ledger
      dockerfile: Dockerfile
    container_name: external-ledger
    ports:
      - "6002:6002"

  gateway-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway-1
    ports:
      - "6001:6001"
    depends_on:
      redis:
        condition: service_started
      external-ledger:
        condition: service_started
    environment:
      SERVER_PORT: 6001
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SYSTEM_B_WS_URL: ws://external-ledger:6002/mock-ws
      SIGNATURE_VERIFICATION_ENABLED: "true"
      SIGNATURE_PUBLIC_KEY_PATH: "classpath:keys/public.pem"
      GATEWAY_INSTANCE_ID: gateway-1
      systema.webhook.url: "http://host.docker.internal:8081/api/v1/webhook"

  gateway-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway-2
    ports:
      - "6003:6001"
    depends_on:
      redis:
        condition: service_started
      external-ledger:
        condition: service_started
    environment:
      SERVER_PORT: 6001
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SYSTEM_B_WS_URL: ws://external-ledger:6002/mock-ws
      SIGNATURE_VERIFICATION_ENABLED: "true"
      SIGNATURE_PUBLIC_KEY_PATH: "classpath:keys/public.pem"
      GATEWAY_INSTANCE_ID: gateway-2
      systema.webhook.url: "http://host.docker.internal:8081/api/v1/webhook"
