services:
  gateway-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "6001:6001"
    depends_on:
      - redis
    environment:
      SERVER_PORT: 6001
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    #mock-websocket-server:
    #build: ./mock-websocket-server
    #container_name: mock-websocket-server
    #ports:
    #  - "8090:8090"
    #gateway-service-2:
    #build: .
    #container_name: gateway-service-2
    #ports:
    #  - "8081:8080"
    #depends_on:
    #  - redis

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"