spring:
  application:
    name: saga-gateway-service
  data:
    redis:
      host: redis
      port: 6379

server:
  port: 6001
signature:
  verification:
    enabled: ${SIGNATURE_VERIFICATION_ENABLED:false}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

